import { ArrowDown, ArrowUpRight, Download, Github, Linkedin, Mail, MapPin } from "lucide-react";
import Image from "next/image";
import { motion } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Reveal } from "./reveal";
import { ProjectGrid } from "./project-grid";
import { AchievementShowcase } from "./achievement-showcase";
import { SkillsCarousel } from "./skills-carousel";
import { IntroVideoPlayer } from "./intro-video-player";
export function Hero(){
  return <section className="relative flex min-h-[calc(100vh-78px)] items-center overflow-hidden">
    <div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_72%_18%,rgba(139,92,246,.16),transparent_30%),radial-gradient(circle_at_12%_65%,rgba(59,130,246,.07),transparent_24%)]"/>
    <div className="absolute right-[8%] top-[24%] -z-10 h-64 w-64 rounded-full bg-violet-500/10 blur-3xl"/>
    <div className="container-main grid w-full items-center gap-10 py-12 lg:grid-cols-[minmax(0,1.15fr)_minmax(320px,.75fr)] lg:gap-10">
      <div>
        <div className="max-w-5xl">
          <div className="mb-5 font-mono text-[11px] tracking-[.2em] text-violet-300">AI/ML ENGINEER · SOFTWARE ENGINEER</div>
          <motion.h1 initial={{y:54,scale:.94}} animate={{y:0,scale:1}} transition={{duration:1,delay:.12,ease:[.22,1,.36,1]}} className="hero-title max-w-5xl text-[clamp(3rem,5.8vw,6rem)] font-semibold leading-[.96] tracking-[-.075em] text-white">I make it work on <span className="tagline-gradient inline-block pr-[.08em] bg-clip-text text-transparent">everybody’s machine.</span></motion.h1>
          <p className="mt-8 max-w-3xl text-lg leading-8 text-zinc-400">I'm Sagar Prajapati, an AI/ML Engineer with hands-on experience across deep learning, computer vision, RAG, LLM applications, backend engineering, distributed systems and DevOps.</p>
          <div className="mt-8 flex flex-wrap gap-3"><Button asChild><a href="#work">Explore my work <ArrowDown size={15}/></a></Button><Button asChild variant="secondary"><a href="mailto:sagarprajapati1374@gmail.com">Get in touch <Mail size={15}/></a></Button></div>
          <div className="mt-10 flex flex-wrap gap-x-7 gap-y-2 font-mono text-[10px] tracking-[.14em] text-zinc-600"><span>INDIA</span><span>B.TECH CSE — AI & ML</span><span>GPA 8.9/10</span><span>IEEE CONFERENCE AUTHOR</span></div>
        </div>
      </div>
      <motion.figure initial={{y:24,scale:.9,rotateY:-14,rotateX:5,borderRadius:40,transformPerspective:1000}} animate={{y:0,scale:1,rotateY:0,rotateX:0,borderRadius:26}} transition={{duration:1.25,delay:.28,ease:[.22,1,.36,1]}} style={{transformStyle:"preserve-3d"}} className="relative mx-auto aspect-[3/4] w-full max-w-[390px] overflow-hidden rounded-[26px] border border-white/10 bg-white/[.04] shadow-2xl shadow-black/30 lg:mr-2 lg:ml-auto">
          <Image src="/images/sagar-prajapati-profile.jpeg" alt="Portrait of Sagar Prajapati" fill priority sizes="(max-width: 1024px) 80vw, 390px" className="scale-[.96] object-contain object-center" />
          <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent px-5 pb-5 pt-12"><figcaption className="font-mono text-[10px] tracking-[.16em] text-white/85">SAGAR PRAJAPATI</figcaption></div>
      </motion.figure>
    </div>
  </section>;
}
export function IntroVideo(){return <section id="intro-video" className="border-t border-white/5 py-20 sm:py-28"><Reveal><div className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-3 font-mono text-[10px] tracking-[.18em] text-violet-300">A QUICK INTRODUCTION</div><h2 className="text-3xl font-semibold tracking-[-.055em] text-white sm:text-5xl">A little more about me.</h2></div><p className="max-w-md text-sm leading-7 text-zinc-400">A short introduction to the person behind the projects.</p></div><div className="relative mx-auto aspect-video w-full max-w-5xl overflow-hidden rounded-2xl border border-white/10 bg-black shadow-2xl shadow-black/30"><IntroVideoPlayer/></div></Reveal></section>}
export function Projects(){return <section id="work" className="border-t border-white/5 py-24 sm:py-32"><Reveal><div className="mb-10 flex flex-col justify-between gap-6 lg:flex-row lg:items-end"><div><div className="mb-3 font-mono text-[10px] tracking-[.18em] text-violet-300">SELECTED PROJECTS</div><h2 className="text-4xl font-semibold tracking-[-.055em] text-white sm:text-6xl">Projects from my resume.</h2></div><p className="max-w-md text-sm leading-7 text-zinc-500">Systems, AI applications, infrastructure and experiments built across research and engineering work.</p></div></Reveal><ProjectGrid/></section>}
const experiences: Array<[string,string,string,string[]]> = [['FEB 2026 — MAY 2026','SDE Intern · CheckRed Security','Pune',['Automated RPM packaging pipelines for RHEL and Rocky Linux using rpmbuild, spec files and Bash.','Developed OVA build workflows for secure, pre-configured VM images.','Debugged build and dependency failures through log analysis.','Integrated CI/CD pipelines for automated build, test and release processes.','Standardized build environments to reduce deployment inconsistencies.']],['AUG 2025 — NOV 2025','Data Science Intern · Wordlane Tech','', ['Built stock-market prediction models using statistical methods and machine learning, with time-series analysis and mathematical feature engineering on raw financial data.']],['MAY 2025 — AUG 2025','AI Research Intern · COEP Technological University','Pune · Data Mining Lab',['Trained a custom CNN for chit-paper detection and behavior tracking, with a reported 27% accuracy improvement.','Optimized PyTorch inference by 40% on NVIDIA DGX systems.','Automated dataset annotation workflows using Roboflow and Python, reducing manual effort by 60%.']],['MAY 2024 — AUG 2024','Web Development Intern · Qwerty Digital Solution','',['Developed and deployed client websites using WordPress and Elementor.']]];
export function Experience(){return <section id="experience" className="border-t border-white/5 py-24 sm:py-32"><div className="grid gap-16 lg:grid-cols-[.65fr_1.35fr] lg:gap-28"><Reveal><div><div className="mb-3 font-mono text-[10px] tracking-[.18em] text-violet-300">WORK EXPERIENCE</div><h2 className="text-4xl font-semibold tracking-[-.055em] text-white sm:text-6xl">Applied AI.<br/>Real systems.</h2></div></Reveal><div className="border-l border-white/10 pl-7 sm:pl-10">{experiences.map(([date,title,place,bullets],i)=><Reveal key={title} delay={i*.06} className="relative pb-12 last:pb-0"><span className="absolute -left-[31px] top-1.5 h-2 w-2 rounded-full bg-violet-400 shadow-[0_0_0_5px_#07070a]"/><div className="font-mono text-[10px] tracking-[.14em] text-zinc-600">{date}</div><h3 className="mt-2 text-xl font-semibold text-zinc-100">{title}</h3>{place&&<p className="mt-1 text-xs text-zinc-500">{place}</p>}<ul className="mt-3 space-y-2 text-sm leading-6 text-zinc-400">{bullets.map(b=><li key={b}>— {b}</li>)}</ul></Reveal>)}</div></div></section>}
export function Achievements(){return <section id="achievements" className="border-t border-white/5 py-24 sm:py-32"><Reveal><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="mb-3 font-mono text-[10px] tracking-[.18em] text-violet-300">ACHIEVEMENTS</div><h2 className="text-4xl font-semibold tracking-[-.055em] text-white sm:text-6xl">Beyond the classroom.</h2></div><p className="max-w-md text-sm leading-7 text-zinc-500">A dedicated record of academic performance, competitive programming, research and recruitment milestones.</p></div></Reveal><AchievementShowcase/></section>}
export function Education(){const education:Array<[string,string,React.ReactNode]>=[['AUG 2022 — MAY 2026','D.Y. Patil International University, Pune',<><strong>B.Tech in Computer Science & Engineering (AI & ML)</strong><br/>Final GPA: 8.9/10</>],['JUN 2020 — MAY 2022','SVKM’s Mithibai College of Arts & Science, Mumbai',<>Higher Secondary — Science</>],['JUN 2009 — APR 2020','New Model English High School, Mumbai',<>SSC — 91.20%</>]];return <section id="education" className="border-t border-white/5 py-24 sm:py-32"><div className="grid gap-16 lg:grid-cols-[.65fr_1.35fr] lg:gap-28"><Reveal><div><div className="mb-3 font-mono text-[10px] tracking-[.18em] text-violet-300">EDUCATION</div><h2 className="text-4xl font-semibold tracking-[-.055em] text-white sm:text-6xl">Computer Science<br/>× AI & ML.</h2></div></Reveal><div className="border-l border-white/10 pl-7 sm:pl-10">{education.map(([date,title,desc],i)=><Reveal key={title} delay={i*.06} className="relative pb-12 last:pb-0"><span className="absolute -left-[31px] top-1.5 h-2 w-2 rounded-full bg-violet-400 shadow-[0_0_0_5px_#07070a]"/><div className="font-mono text-[10px] tracking-[.14em] text-zinc-600">{date}</div><h3 className="mt-2 text-xl font-semibold text-zinc-100">{title}</h3><p className="mt-2 text-sm leading-6 text-zinc-400">{desc}</p></Reveal>)}</div></div></section>}
export function Resume(){return <section id="resume" className="border-t border-white/5 py-24 sm:py-32"><Reveal><div className="rounded-3xl border border-white/10 bg-gradient-to-br from-white/[.05] to-transparent p-7 sm:p-10"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><div className="mb-3 font-mono text-[10px] tracking-[.18em] text-violet-300">RESUME</div><h2 className="text-3xl font-semibold tracking-[-.04em] text-white sm:text-4xl">My resume, one click away.</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-zinc-400">View or download the portfolio edition of my latest resume.</p></div><div className="flex flex-wrap gap-3"><Button asChild><a href="/SagarPrajapatiResume_2026_With_Portfolio%20%281%29.pdf" target="_blank" rel="noreferrer">Open Resume <Download size={15}/></a></Button><Button asChild variant="secondary"><a href="/SagarPrajapatiResume_2026_With_Portfolio%20%281%29.pdf" download>Download PDF</a></Button></div></div><div className="mt-6 font-mono text-[10px] text-zinc-500">2-page PDF · Portfolio edition</div></div><div className="mt-6" aria-label="Resume first-page preview">
      <figure className="relative m-0 w-full overflow-hidden rounded-2xl border border-white/10 bg-white shadow-xl shadow-black/20" style={{ aspectRatio: "1041 / 900" }}>
        <a href="/SagarPrajapatiResume_2026_With_Portfolio%20%281%29.pdf" target="_blank" rel="noreferrer" aria-label="Open Sagar Prajapati's full two-page resume" className="group absolute inset-0 block overflow-hidden">
          <Image src="/images/resume/page-1.webp" alt="Resume preview, showing the first two-thirds of page one" width={1041} height={1347} sizes="100vw" className="absolute left-0 top-0 block h-auto w-full max-w-none bg-white" />
          <span className="absolute inset-x-0 bottom-0 z-10 bg-gradient-to-t from-[#07070a]/90 to-transparent px-5 pb-5 pt-16 text-center font-mono text-[10px] font-medium tracking-[.12em] text-white transition-colors group-hover:text-violet-200">CLICK TO VIEW THE FULL TWO-PAGE RESUME ?</span>
        </a>
      </figure>
    </div></Reveal></section>}
export function About(){return <section id="about" className="border-t border-white/5 py-24 sm:py-32"><Reveal><div className="max-w-5xl"><div className="mb-3 font-mono text-[10px] tracking-[.18em] text-violet-300">ENGINEERING PROFILE</div><h2 className="text-4xl font-semibold tracking-[-.055em] text-white sm:text-6xl">From models to infrastructure.</h2><p className="mt-7 max-w-4xl text-lg leading-8 text-zinc-400">My work spans AI research, production-oriented GenAI systems, backend engineering, distributed systems and Linux/DevOps automation. I enjoy taking an idea from architecture through implementation, testing, observability and deployment.</p><SkillsCarousel/></div></Reveal></section>}
export function Contact(){return <section id="contact" className="border-t border-white/5 py-28 text-center sm:py-36"><Reveal><div className="mb-3 font-mono text-[10px] tracking-[.18em] text-violet-300">LET’S BUILD</div><h2 className="mx-auto max-w-4xl text-4xl font-semibold leading-tight tracking-[-.055em] text-white sm:text-6xl">Looking for an engineer who likes <span className="text-violet-300">both models and systems?</span></h2><div className="mt-8 flex flex-wrap justify-center gap-3"><Button asChild><a href="mailto:sagarprajapati1374@gmail.com">Email me <Mail size={15}/></a></Button><Button asChild variant="secondary"><a href="https://github.com/unknown07ps" target="_blank" rel="noreferrer">GitHub <Github size={15}/></a></Button><Button asChild variant="secondary"><a href="https://www.linkedin.com/in/sagar-prajapati-7b99822b4/" target="_blank" rel="noreferrer">LinkedIn <Linkedin size={15}/></a></Button><Button asChild variant="secondary"><a href="#resume">View Resume <ArrowUpRight size={15}/></a></Button></div></Reveal></section>}
