"use client";
import { Github, Linkedin, Mail } from "lucide-react";
import { ThemeToggle } from "@/app/components/theme-toggle";
import { Hero, IntroVideo, Projects, Experience, Achievements, Education, Resume, About, Contact } from "@/app/components/sections";
import { DsaJourney } from "@/app/components/dsa-journey";
export default function Page(){return <><header className="sticky top-0 z-50 h-[78px] border-b border-white/[.08] bg-[#08080a]/95 backdrop-blur-xl">
<div className="container-main relative grid h-full grid-cols-[1fr_auto] items-center md:grid-cols-[1fr_auto_1fr]">
<a href="#top" aria-label="Sagar Prajapati home" className="grid h-11 w-11 place-items-center rounded-full border border-white/25 bg-white/[.03] text-[14px] font-extrabold tracking-[-.08em] text-white transition hover:-rotate-6 hover:border-violet-300/60">SP<span className="text-violet-300">.</span></a>
<nav aria-label="Main navigation" className="hidden items-center gap-5 whitespace-nowrap md:flex lg:gap-7">{[['About','#about'],['Work','#work'],['DSA','#dsa'],['Experience','#experience'],['Achievements','#achievements'],['Contact','#contact']].map(([label,href])=><a key={href} href={href} className="text-[11px] text-zinc-400 transition hover:text-white">{label}</a>)}</nav>
<div className="hidden items-center justify-self-end gap-2 md:flex">
<a href="https://github.com/unknown07ps" target="_blank" rel="noreferrer" aria-label="GitHub profile" title="GitHub" className="grid h-9 w-9 place-items-center rounded-full text-zinc-400 transition hover:-translate-y-0.5 hover:bg-white/[.06] hover:text-white"><Github size={17}/></a>
<a href="https://www.linkedin.com/in/sagar-prajapati-7b99822b4/" target="_blank" rel="noreferrer" aria-label="LinkedIn profile" title="LinkedIn" className="grid h-9 w-9 place-items-center rounded-full text-zinc-400 transition hover:-translate-y-0.5 hover:bg-white/[.06] hover:text-white"><Linkedin size={17}/></a>
<a href="mailto:sagarprajapati1374@gmail.com" aria-label="Email Sagar" title="Email" className="grid h-9 w-9 place-items-center rounded-full text-zinc-400 transition hover:-translate-y-0.5 hover:bg-white/[.06] hover:text-white"><Mail size={17}/></a>
<a href="#intro-video" className="ml-1 rounded-full border border-violet-300/30 bg-violet-300/10 px-3.5 py-2 text-[11px] text-violet-100 transition hover:border-violet-200/60 hover:bg-violet-300/20">Video intro</a><a href="#resume" className="rounded-full border border-white/10 bg-white/[.04] px-3.5 py-2 text-[11px] text-white transition hover:border-violet-300/40 hover:bg-violet-300/10">Resume</a><ThemeToggle/>
</div>
<div className="flex items-center gap-2 md:hidden">
<details className="relative"><summary className="cursor-pointer list-none rounded-full border border-white/10 px-3.5 py-2 font-mono text-[10px] tracking-[.1em] text-zinc-200 [&::-webkit-details-marker]:hidden">MENU</summary><nav aria-label="Mobile navigation" className="absolute right-0 top-[calc(100%+12px)] z-[60] w-[min(280px,calc(100vw-32px))] rounded-2xl border border-white/10 bg-[#101014] p-2 shadow-2xl shadow-black/50">{[['About','#about'],['Work','#work'],['DSA','#dsa'],['Experience','#experience'],['Achievements','#achievements'],['Contact','#contact']].map(([label,href])=><a key={href} href={href} className="block rounded-lg px-3 py-2.5 text-sm text-zinc-300 hover:bg-white/[.06] hover:text-white">{label}</a>)}<div className="mt-2 flex gap-2 border-t border-white/10 px-2 pt-2"><a href="https://github.com/unknown07ps" target="_blank" rel="noreferrer" aria-label="GitHub profile" className="grid h-9 w-9 place-items-center rounded-full text-zinc-300 hover:bg-white/[.06]"><Github size={16}/></a><a href="https://www.linkedin.com/in/sagar-prajapati-7b99822b4/" target="_blank" rel="noreferrer" aria-label="LinkedIn profile" className="grid h-9 w-9 place-items-center rounded-full text-zinc-300 hover:bg-white/[.06]"><Linkedin size={16}/></a><a href="mailto:sagarprajapati1374@gmail.com" aria-label="Email Sagar" className="grid h-9 w-9 place-items-center rounded-full text-zinc-300 hover:bg-white/[.06]"><Mail size={16}/></a></div><a href="#resume" className="mt-1 block rounded-lg px-3 py-2.5 text-sm text-zinc-300 hover:bg-white/[.06]">Resume</a></nav></details><ThemeToggle/>
</div>
</div></header><main id="top" className="container-main"><Hero/><Projects/><IntroVideo/><DsaJourney/><Experience/><Achievements/><Education/><Resume/><About/><Contact/></main><footer className="container-main flex flex-col gap-3 border-t border-white/5 py-8 font-mono text-[10px] tracking-wider text-zinc-600 sm:flex-row sm:justify-between"><span>© 2026 Sagar Prajapati</span><span>AI · Systems · Software</span></footer></>}


